let PRODUCTS = [
  {id:'l-101',name:'Lentis Atelier 01',category:'vedere',type:'Rame de vedere',fit:'Unisex · Acetat premium',price:289,oldPrice:null,tag:'Favorit',image:'frame-01.svg'},
  {id:'l-102',name:'Lentis Milano',category:'soare',type:'Ochelari de soare',fit:'Unisex · Design urban',price:349,oldPrice:429,tag:'-19%',image:'frame-03.svg'},
  {id:'l-103',name:'Lentis Signature',category:'vedere',type:'Rame de vedere',fit:'Damă · Formă soft-square',price:319,oldPrice:null,tag:'Nou',image:'frame-02.svg'},
  {id:'l-104',name:'Lentis Clear Day',category:'lentile',type:'Lentile de contact',fit:'Concept ilustrativ · Lentile',price:119,oldPrice:null,tag:'Concept',image:'contact.svg'},
  {id:'l-105',name:'Lentis Neo',category:'vedere',type:'Rame de vedere',fit:'Bărbați · Metal & acetat',price:259,oldPrice:null,tag:'Nou',image:'frame-05.svg'},
  {id:'l-106',name:'Lentis Eclipse',category:'soare',type:'Ochelari de soare',fit:'Unisex · Stil contemporan',price:389,oldPrice:469,tag:'-17%',image:'frame-04.svg'},
  {id:'l-107',name:'Lentis Blue Line',category:'vedere',type:'Rame de vedere',fit:'Unisex · Minimal',price:239,oldPrice:null,tag:'Popular',image:'frame-01.svg'},
  {id:'l-108',name:'Lentis Air',category:'lentile',type:'Lentile de contact',fit:'Concept ilustrativ · Confort',price:139,oldPrice:null,tag:'Concept',image:'contact.svg'}
];
const safeRead = (key, fallback) => { try { const v = JSON.parse(localStorage.getItem(key)); return v ?? fallback; } catch {return fallback;} };
const state = {filter:'toate',query:'',sort:'featured',cart:safeRead('lentis-cart-v1',{}),favorites:safeRead('lentis-favorites-v1',[]),drawer:'cart'};
const $ = (sel) => document.querySelector(sel);
const icon = (id) => `<svg aria-hidden="true"><use href="#i-${id}"/></svg>`;
const money = (n) => `${Number(n).toLocaleString('ro-RO')} lei`;
const esc = text => String(text ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const productImg = product => product.image_url && /^https:\/\/[^\s"'<>]+$/i.test(product.image_url) ? product.image_url : './assets/'+encodeURIComponent(product.image || 'frame-01.svg');
function saveState(){localStorage.setItem('lentis-cart-v1',JSON.stringify(state.cart));localStorage.setItem('lentis-favorites-v1',JSON.stringify(state.favorites));updateCounts();}
function updateCounts(){let count=Object.values(state.cart).reduce((sum,n)=>sum+n,0);$('#cartCount').textContent=count;$('#cartCount').hidden=count===0;$('#favoritesCount').textContent=state.favorites.length;$('#favoritesCount').hidden=!state.favorites.length;}
function renderProducts(){const q=state.query.trim().toLocaleLowerCase('ro-RO');let products=PRODUCTS.filter(p=>(state.filter==='toate'||state.filter===p.category)&&(!q||`${esc(p.name)} ${p.category} ${esc(p.type)} ${esc(p.fit)}`.toLocaleLowerCase('ro-RO').includes(q)));if(state.sort==='asc')products.sort((a,b)=>a.price-b.price);if(state.sort==='desc')products.sort((a,b)=>b.price-a.price);$('#products').innerHTML=products.map(p=>`<article class="product-card"><div class="product-media"><img src="${productImg(p)}" alt="${esc(p.type)} model ${esc(p.name)}" loading="lazy" /><span class="product-tag ${p.oldPrice?'discount':''}">${esc(p.tag)}</span><button class="wishlist ${state.favorites.includes(p.id)?'is-active':''}" type="button" data-wishlist="${esc(p.id)}" aria-label="${state.favorites.includes(p.id)?'Elimină de la':'Adaugă la'} favorite ${esc(p.name)}" aria-pressed="${state.favorites.includes(p.id)}">${icon('heart')}</button></div><div class="product-body"><small>${esc(p.type)}</small><h3>${esc(p.name)}</h3><p>${esc(p.fit)}</p><div class="price-line"><strong>${money(p.price)}</strong>${p.oldPrice?`<del>${money(p.oldPrice)}</del>`:''}</div><button type="button" class="product-add" data-add="${esc(p.id)}">${icon('cart')} Adaugă în coș</button></div></article>`).join('');$('#emptyState').hidden=!!products.length;}
function setFilter(value){state.filter=value;document.querySelectorAll('[data-filter]').forEach(el=>el.classList.toggle('active',el.dataset.filter===value));renderProducts();}
let toastTimer;function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),3000);}
function addCart(id){state.cart[id]=(state.cart[id]||0)+1;saveState();toast('Produs adăugat în coșul demonstrativ.');}
function toggleFavorite(id){state.favorites=state.favorites.includes(id)?state.favorites.filter(v=>v!==id):[...state.favorites,id];saveState();renderProducts();if(!$('#drawer').hidden && state.drawer==='favorites')renderDrawer();}
function openDrawer(which){state.drawer=which;$('#drawerTitle').textContent=which==='cart'?'Coșul meu':'Favoritele mele';$('#overlay').hidden=false;$('#drawer').hidden=false;document.body.style.overflow='hidden';renderDrawer();$('#drawer .close-button').focus();}
function closeDrawer(){ $('#overlay').hidden=true;$('#drawer').hidden=true;document.body.style.overflow=''; }
function renderDrawer(){const items=state.drawer==='favorites'?PRODUCTS.filter(p=>state.favorites.includes(p.id)):PRODUCTS.filter(p=>state.cart[p.id]>0);const content=$('#drawerContent'),footer=$('#drawerFooter');if(!items.length){content.innerHTML=`<div class="drawer-empty">${icon(state.drawer==='cart'?'cart':'heart')}<h3>${state.drawer==='cart'?'Coșul este gol':'Nu ai favorite încă'}</h3><p>Explorează produsele Lentis și adaugă ce îți place.</p><button class="button button-primary" type="button" data-action="go-shop">Vezi colecția ${icon('arrow')}</button></div>`;footer.innerHTML='';return;}
content.innerHTML=items.map(p=>`<div class="cart-item"><img src="${productImg(p)}" alt="${esc(p.name)}"/><div><h3>${esc(p.name)}</h3><p>${money(p.price)}</p><div class="qty-row">${state.drawer==='cart'?`<div class="qty-buttons"><button type="button" data-qty="${esc(p.id)}" data-amount="-1" aria-label="Scade cantitatea">−</button><strong>${state.cart[p.id]}</strong><button type="button" data-qty="${esc(p.id)}" data-amount="1" aria-label="Crește cantitatea">+</button></div>`:''}<button class="text-link" type="button" data-remove="${esc(p.id)}">Elimină</button></div></div></div>`).join('');footer.innerHTML=state.drawer==='cart'?`<div class="cart-total"><span>Total estimativ</span><strong>${money(items.reduce((total,p)=>total+p.price*state.cart[p.id],0))}</strong></div><button class="button button-primary" type="button" data-action="checkout">Continuă ${icon('arrow')}</button><span class="form-note">Coș de demonstrație. Nu se efectuează plăți sau comenzi.</span>`:`<button class="button button-primary" type="button" data-action="go-shop">Continuă cumpărăturile ${icon('arrow')}</button>`;}
function showModal(html){const modal=$('#modal');$('#modalContent').innerHTML=html;modal.showModal();}
function bookingModal(){showModal(`<div class="eyebrow">LENTIS · OPTICĂ MEDICALĂ MOBILĂ</div><h2>Vedere clară, oriunde ai nevoie!</h2><p>Solicită telefonic o consultație optometrică, inclusiv la tine acasă sau la firmă. Echipa îți confirmă aria de acoperire, disponibilitatea și condițiile serviciului.</p><div class="modal-features"><div class="modal-feature">${icon('eye')} Consultații optometrice</div><div class="modal-feature">${icon('pin')} Prel. Ghencea 94–100, Sector 6</div><div class="modal-feature">${icon('user')} Andrei Hâlcu · Tehnician optometrist</div><div class="modal-feature">${icon('glasses')} Ochelari & lentile de contact</div></div><a href="tel:+40774987055" class="button button-primary">Sună la 0774 987 055 ${icon('arrow')}</a><span class="form-note">Programările sunt confirmate exclusiv telefonic. Site-ul nu rezervă automat intervale.</span>`);}
function partnerModal(){showModal(`<div class="eyebrow">PARTENERIATE LENTIS</div><h2>Clinica ta. Mai aproape de clienți.</h2><p>Completează formularul pentru a testa experiența de înscriere. Poți trimite o cerere de parteneriat când este activă integrarea securizată. Până atunci, contactează-ne telefonic.</p><form id="partnerForm"><label for="clinicName">Numele clinicii / opticii</label><input id="clinicName" name="clinic" required maxlength="90" placeholder="Ex. Optică București"/><label for="contactName">Persoană de contact</label><input id="contactName" name="contact" required maxlength="90" placeholder="Nume și prenume"/><label for="contactEmail">Email</label><input type="email" id="contactEmail" name="email" required maxlength="120" placeholder="contact@clinica.ro"/><label for="city">Oraș</label><input id="city" name="city" required maxlength="80" placeholder="București"/><label class="consent"><input type="checkbox" name="consent" required/> Sunt de acord cu prelucrarea datelor pentru a fi contactat în legătură cu parteneriatul. În modul demo, datele se salvează doar în acest browser.</label><button class="button button-primary" type="submit">Salvează testul formularului ${icon('arrow')}</button><span class="form-note">Pentru discuția despre un parteneriat real, sună la 0774 987 055.</span><div id="partnerMessage" aria-live="polite"></div></form>`);}
function tryonModal(){ if(window.LentisTryOn) window.LentisTryOn.open(); else toast("Proba virtuală se încarcă. Reîncearcă."); }
function checkoutModal(){closeDrawer();showModal(`<div class="eyebrow">LENTIS SHOP / DEMO</div><h2>Magazinul prinde contur.</h2><p>Coșul și produsele funcționează ca demonstrație interactivă. Nu poți plasa încă o comandă sau efectua o plată. Următorul pas este integrarea stocurilor reale, a comenzilor și a procesatorului de plăți.</p><button class="button button-primary" data-action="modal-shop" type="button">Înapoi la produse ${icon('arrow')}</button>`);}
function hideMobile(){ $('#mobileNav').hidden=true;document.querySelector('[data-action="mobile-menu"]').setAttribute('aria-expanded','false'); }
document.addEventListener('click',(e)=>{
const add=e.target.closest('[data-add]');if(add){addCart(add.dataset.add);return;}
const favorite=e.target.closest('[data-wishlist]');if(favorite){toggleFavorite(favorite.dataset.wishlist);return;}
const filter=e.target.closest('[data-filter]');if(filter){setFilter(filter.dataset.filter);return;}
const cat=e.target.closest('[data-category-link],[data-nav-category]');if(cat){setFilter(cat.dataset.categoryLink||cat.dataset.navCategory);hideMobile();return;}
const qty=e.target.closest('[data-qty]');if(qty){const id=qty.dataset.qty;const next=(state.cart[id]||0)+Number(qty.dataset.amount);if(next<=0)delete state.cart[id];else state.cart[id]=next;saveState();renderDrawer();return;}
const remove=e.target.closest('[data-remove]');if(remove){if(state.drawer==='cart')delete state.cart[remove.dataset.remove];else state.favorites=state.favorites.filter(v=>v!==remove.dataset.remove);saveState();renderDrawer();renderProducts();return;}
const action=e.target.closest('[data-action]')?.dataset.action;if(!action)return;
if(action==='cart'||action==='favorites')openDrawer(action);
if(action==='close')closeDrawer();
if(action==='modal-close')$('#modal').close();
if(action==='go-shop'){closeDrawer();location.hash='#shop';}
if(action==='booking')bookingModal();
if(action==='partner')partnerModal();
if(action==='tryon')tryonModal();
if(action==='checkout')checkoutModal();
if(action==='mobile-menu'){const nav=$('#mobileNav');nav.hidden=!nav.hidden;e.target.closest('button').setAttribute('aria-expanded',String(!nav.hidden));}
if(action==='search-focus'){location.hash='#shop';$('#productSearch').focus();}
if(action==='modal-shop'){$('#modal').close();location.hash='#shop';}
});
document.addEventListener('submit',(e)=>{if(e.target.id!=='partnerForm')return;e.preventDefault();const data=Object.fromEntries(new FormData(e.target));if(!data.consent)return;if(window.LentisPlatform?.partnerSubmissionEnabled){window.LentisPlatform.submitPartner(data).then(()=>{$('#partnerMessage').textContent='Cererea a fost trimisă echipei Lentis.';e.target.reset();}).catch(()=>{$('#partnerMessage').textContent='Nu am putut trimite cererea. Te rugăm să suni la 0774 987 055.';});return;}const entries=safeRead('lentis-partners-demo-v1',[]);entries.push({clinic:data.clinic,contact:data.contact,email:data.email,city:data.city,createdAt:new Date().toISOString()});localStorage.setItem('lentis-partners-demo-v1',JSON.stringify(entries));$('#partnerMessage').innerHTML='<div class="form-success">Formular demonstrativ salvat în acest browser. Nu a fost trimis către Lentis. Pentru înscriere reală, contactează echipa telefonic.</div>';e.target.reset();});
$('#overlay').addEventListener('click',closeDrawer);
$('#productSearch').addEventListener('input',(e)=>{state.query=e.target.value;renderProducts();});
$('#sortProducts').addEventListener('change',(e)=>{state.sort=e.target.value;renderProducts();});
$('#resetFilters').addEventListener('click',()=>{state.query='';$('#productSearch').value='';setFilter('toate');});
document.querySelectorAll('.mobile-nav a').forEach(a=>a.addEventListener('click',hideMobile));
document.addEventListener('keydown',(e)=>{if(e.key==='Escape')closeDrawer();});
$('#year').textContent=new Date().getFullYear();
// Adjust old local data safely across versions, while retaining non-negative integer counts.
state.cart=Object.fromEntries(Object.entries(state.cart).filter(([id,n])=>PRODUCTS.some(p=>p.id===id)&&Number.isInteger(n)&&n>0&&n<100));state.favorites=Array.isArray(state.favorites)?state.favorites.filter(id=>PRODUCTS.some(p=>p.id===id)):[];updateCounts();renderProducts();
window.LentisCatalogUpdate = function(rows){
 if(!Array.isArray(rows)) return;
 PRODUCTS=rows.filter(r=>r.published&&Number.isFinite(Number(r.price))).map(r=>({id:r.id,name:String(r.name||'').slice(0,120),category:r.category,type:({vedere:'Rame de vedere',soare:'Ochelari de soare',lentile:'Lentile de contact'})[r.category]||'Ochelari',fit:String(r.description||'').slice(0,240),price:Number(r.price),oldPrice:null,tag:String(r.tag||'').slice(0,50),image:'frame-01.svg',image_url:r.image_url||''}));
 state.cart=Object.fromEntries(Object.entries(state.cart).filter(([id])=>PRODUCTS.some(p=>p.id===id)));
 state.favorites=state.favorites.filter(id=>PRODUCTS.some(p=>p.id===id));saveState();renderProducts();
};